## 作業目標：運用scikit-learn API 實現K-fold分割資料

---

### 讀入資料

In [1]:
import pandas as pd
dataset = pd.read_csv(r'Social_Network_Ads.csv')

In [2]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

### 取出訓練特徵與標註

In [3]:
X = dataset[['User ID', 'Gender', 'Age', 'EstimatedSalary']].values
Y = dataset['Purchased'].values

---

In [4]:
import numpy as np
from sklearn.model_selection import KFold

### 將訓練資料按照順序切割成10等分

In [5]:
kf = KFold(n_splits=10)
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=None, shuffle=False)


### 將訓練資料隨機切割成10等分

In [6]:
kf = KFold(n_splits=10, random_state=None, shuffle=True)
kf.get_n_splits(X)

print(kf)

KFold(n_splits=10, random_state=None, shuffle=True)


### 取出 切割資料對應位置

In [7]:
train_split = kf.split(X)
next(train_split)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         41,  42,  43,  44,  45,  46,  47,  48,  50,  51,  52,  53,  54,
         55,  56,  57,  59,  60,  61,  62,  63,  64,  65,  66,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
         83,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
         97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
        110, 111, 112, 113, 117, 119, 120, 121, 122, 123, 124, 125, 127,
        128, 130, 131, 132, 133, 134, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 156,
        158, 159, 160, 162, 163, 164, 165, 166, 169, 170, 172, 173, 175,
        176, 177, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
        190, 191, 192, 193, 194, 195, 196, 197, 198

### Or

In [8]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  62  63  64  65  66  67  68  69  70  71  72  73  75
  76  77  78  79  80  82  83  84  85  86  88  89  90  92  93  94  95  96
  97  98  99 100 101 102 103 105 106 107 108 109 110 111 112 114 115 116
 117 118 119 120 121 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 148 149 150 151 152 153 154 155
 157 158 159 160 162 163 165 166 167 168 169 170 173 174 175 176 177 178
 179 180 181 182 183 184 185 186 187 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 208 209 210 211 213 214 215 216 217
 218 220 221 222 223 225 226 227 228 229 230 232 234 235 236 237 238 239
 240 241 242 243 244 245 246 248 249 250 251 252 253 254 255 256 257 258
 259 260 261 263 264 265 268 269 270 271 272

### 取出切割資料：trainset / testset 特徵(x_train/x_test)/標註(y_train/y_test)

In [9]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

In [10]:
X_train

array([[15810944, 'Male', 35.0, 20000.0],
       [15668575, 'Female', 26.0, 43000.0],
       [15603246, 'Female', 27.0, 57000.0],
       ...,
       [15654296, 'Female', 50.0, 20000.0],
       [15755018, 'Male', 36.0, 33000.0],
       [15594041, 'Female', 49.0, 36000.0]], dtype=object)

In [11]:
X_test

array([[15624510, 'Male', 19.0, 19000.0],
       [15736760, 'Female', 47.0, 49000.0],
       [15631159, 'Male', 47.0, 20000.0],
       [15633531, 'Female', 47.0, 30000.0],
       [15782806, 'Female', 27.0, 31000.0],
       [15715541, 'Female', 28.0, 84000.0],
       [15776348, 'Female', 27.0, 54000.0],
       [15744919, 'Female', 29.0, 83000.0],
       [15667265, 'Female', 28.0, 87000.0],
       [15665416, 'Female', 39.0, 71000.0],
       [15591433, 'Male', 36.0, 52000.0],
       [15792102, 'Female', 26.0, 84000.0],
       [15638963, 'Female', 21.0, 68000.0],
       [15800061, 'Female', 28.0, 55000.0],
       [15699247, 'Male', 31.0, 76000.0],
       [15610140, 'Female', 31.0, 15000.0],
       [15762605, 'Male', 26.0, 30000.0],
       [15579781, 'Female', 29.0, 47000.0],
       [15587013, 'Male', 21.0, 88000.0],
       [15614420, 'Female', 23.0, 28000.0],
       [15689751, 'Male', 28.0, 89000.0],
       [15628523, 'Male', 35.0, 39000.0],
       [15809347, 'Female', 41.0, 71000.0],
    

In [12]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,

In [13]:
y_test

array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0], dtype=int64)