### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_numpy() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 - *your function to illustrate*

In [4]:
# Example 1 - ### your explanation ###
x_tensor = torch.randn(2,3)
x_tensor

tensor([[ 0.5967, -0.7737,  0.5849],
        [ 0.6894, -0.4391, -1.0625]])

In [5]:
y_numpy = np.random.randn(2,3)
y_numpy

array([[-1.10424205,  0.57708049, -1.22077983],
       [ 0.95333663,  0.15823454, -0.72674037]])

In [6]:
# Example 2 - ### your explanation ###
x_numpy = x_tensor.numpy()
x_numpy

array([[ 0.59666497, -0.77374125,  0.5848572 ],
       [ 0.6893676 , -0.4390599 , -1.0624943 ]], dtype=float32)

In [7]:
y_tensor = torch.from_numpy(y_numpy)
y_tensor

tensor([[-1.1042,  0.5771, -1.2208],
        [ 0.9533,  0.1582, -0.7267]], dtype=torch.float64)

### Function 2 - your function to illustrate

In [8]:
# Example 1 - ### your explanation ###
a = torch.randn(1,3)
print(a)
print(a.shape)

tensor([[ 0.6997, -0.8491, -0.4898]])
torch.Size([1, 3])


In [9]:
g = torch.unsqueeze(a, dim=1) #增加維度在1的位置
h = torch.squeeze(g) #壓縮為度為1的位置
print(g.shape, h.shape)

torch.Size([1, 1, 3]) torch.Size([3])


In [10]:
b = torch.unsqueeze(a,2)
b

tensor([[[ 0.6997],
         [-0.8491],
         [-0.4898]]])

In [11]:
c = a.unsqueeze(0)
c

tensor([[[ 0.6997, -0.8491, -0.4898]]])

In [12]:
# Example 2 - ### your explanation ###
d = torch.squeeze(c)
d

tensor([ 0.6997, -0.8491, -0.4898])

### Function 3 - your function to illustrate

In [13]:
# Example 1 - ### your explanation ###
x = torch.randn(2,3)
x

tensor([[-0.6977,  0.4742,  1.5085],
        [-0.6398, -0.9820,  0.8557]])

In [14]:
x1 = x.transpose(1,0)
x1

tensor([[-0.6977, -0.6398],
        [ 0.4742, -0.9820],
        [ 1.5085,  0.8557]])

In [15]:
# Example 2 - ### your explanation ###
x5 = x.permute(0,1)
x5

tensor([[-0.6977,  0.4742,  1.5085],
        [-0.6398, -0.9820,  0.8557]])

In [16]:
x6 = x.permute(1,0)
x6

tensor([[-0.6977, -0.6398],
        [ 0.4742, -0.9820],
        [ 1.5085,  0.8557]])

### Function 4 - your function to illustrate

In [17]:
# Example 1 - ### your explanation ###
a = torch.tensor([[[1,2,3],[4,5,6]]])
a

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [18]:
a.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
b = torch.tensor([1,2,3,4,5,6])
b

tensor([1, 2, 3, 4, 5, 6])

In [20]:
b.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [21]:
# Example 2 - ### your explanation ###
x = torch.arange(4.)
shape = (2,2)
y = torch.reshape(x,shape) 

In [22]:
x

tensor([0., 1., 2., 3.])

In [23]:
y

tensor([[0., 1.],
        [2., 3.]])